#!/bin/bash -x 

FlywheelDir=/flywheel/v0
InputDir=${FlywheelDir}/input
OutputDir=${FlywheelDir}/output
Template=${FlywheelDir}/template_description.json
NetworkDir=$FlywheelDir/atlases

[ -d "$OutputDir" ] || mkdir "$OutputDir"

python pet_quants.py -o "$OutputDir" -N $NetworkDir -t $Template ${InputDir}/pet/sub-119517_ses-20221010x1514_trc-PI2620_rec-adyn_pet.nii.gz ${InputDir}/T1
